Repository newlecture-corp/newtil-css, pull requests merged in 2024-02, with the labels that each got.

#10 font 컴포넌트 추가
  packages/css/component/font.css
Labels: feature

#24 토글 컴포넌트 변수 prefix 제거
  packages/css/component/toggle.css
Labels: fix

#26 fix: favicon 및 문서 작성 전초작업
  docs/.vitepress/config.ts
  docs/guide/getting-started-component.md
  docs/guide/getting-started-utility.md
  docs/guide/getting-started.md
Labels: documentation, fix

#27 시작하기를 친절하게
  docs/guide/getting-started.md
Labels: documentation

#28 폼 컴포넌트 추가
  packages/css/component/form.css
Labels: feature

#29 feat:문서 테마 스타일 수정
  docs/.vitepress/theme/style.css
  docs/index.md
  docs/public/favicon.ico
  docs/public/logo-large.webp
  docs/public/logo.png
Labels: feature

#30 fix: cdn 버전 명시
  docs/.vitepress/config.ts
Labels: fix

#33 docs: icon, deco
  docs/.vitepress/config.ts
  docs/icons/getting-started.md
  docs/icons/list.md
Labels: documentation

#32 문서 및 css 수정
  docs/guide/getting-started-utility.md
  packages/css/component/table.css
  packages/css/style.css
Labels: documentation

#34 root.css gap 단위 변경 및 width,height 변수 추가, util 반영
  packages/css/root.css
  packages/css/util/height.css
  packages/css/util/width.css
Labels: feature

#35 버튼 기본 타입을 filled로 변경
  packages/css/component/button.css
Labels: feature

#38 feat: n-list의 type, n-list-item의 padding, border-radius 추가
  packages/css/component/item.css
  packages/css/component/list.css
Labels: feature

#39 feat: 아이콘 추가
  docs/icons/list.md
  docs/shared/icon-list.json
  packages/css/icon.css
  packages/icon/code.svg
  packages/icon/code_simple.svg
  packages/icon/crop.svg
  packages/icon/database.svg
  packages/icon/dots_six.svg
  packages/icon/dots_six_vertical.svg
  packages/icon/gift.svg
  packages/icon/globe.svg
  packages/icon/graduation_cap.svg
  packages/icon/headset.svg
  packages/icon/heart.svg
  packages/icon/heart_fill.svg
  packages/icon/list_bullets.svg
  packages/icon/sliders.svg
  packages/icon/sliders_horizontal.svg
  packages/icon/stack.svg
  packages/icon/tag.svg
  packages/icon/text_a_underline.svg
  packages/icon/text_aa.svg
  packages/icon/text_align_center.svg
  packages/icon/text_align_justify.svg
  packages/icon/text_align_left.svg
  packages/icon/text_align_right.svg
  packages/icon/text_b.svg
  packages/icon/text_strikethrough.svg
  packages/icon/text_t.svg
  packages/icon/text_underline.svg
  packages/icon/trophy.svg
Labels: feature

#41 release 0.1.2
  README.md
  dist/icon/code.svg
  dist/icon/code_simple.svg
  dist/icon/crop.svg
  dist/icon/database.svg
  dist/icon/dots_six.svg
  dist/icon/dots_six_vertical.svg
  dist/icon/gift.svg
  dist/icon/globe.svg
  dist/icon/graduation_cap.svg
  dist/icon/headset.svg
  dist/icon/heart.svg
  dist/icon/heart_fill.svg
  dist/icon/list_bullets.svg
  dist/icon/sliders.svg
  dist/icon/sliders_horizontal.svg
  dist/icon/stack.svg
  dist/icon/tag.svg
  dist/icon/text_a_underline.svg
  dist/icon/text_aa.svg
  dist/icon/text_align_center.svg
  dist/icon/text_align_justify.svg
  dist/icon/text_align_left.svg
  dist/icon/text_align_right.svg
  dist/icon/text_b.svg
  dist/icon/text_strikethrough.svg
  dist/icon/text_t.svg
  dist/icon/text_underline.svg
  dist/icon/trophy.svg
  dist/style.css
  docs/.vitepress/config.ts
  docs/guide/getting-started.md
  package.json
  rollup.config.js
Labels: feature

#42 도트 토글, 아웃라인 토글 버그 수정
  packages/css/component/toggle.css
Labels: fix

#43 feat: 0.1.3
  dist/style.css
  docs/.vitepress/config.ts
  docs/guide/getting-started.md
  package.json
Labels: feature

#45 release 0.1.4
  dist/style.css
  docs/.vitepress/config.ts
  docs/guide/getting-started.md
  package-lock.json
  package.json
Labels: feature

#48 토글 컴포넌트 라벨 gap 4px -> 8px 수정
  packages/css/component/toggle.css
Labels: fix

#49 feat: button-size:3 font-size 추가
  packages/css/component/button.css
Labels: feature

#46 문서 작성 및 컴포넌트 추가, 수정
  docs/.vitepress/config.ts
  docs/component/overview.md
  docs/guide/getting-started-component.md
  docs/guide/getting-started-utility.md
  packages/css/component/table.css
Labels: documentation

#50 텍스트박스 컴포넌트 추가
  packages/css/component/text-box.css
  packages/css/style.css
Labels: feature

#51 텍스트박스 컴포넌트 기본 타입 클래스 추가
  packages/css/component/text-box.css
Labels: fix

#52 텍스트박스 컴포넌트 라벨 기본 위치 오른쪽 -> 왼쪽 변경
  packages/css/component/text-box.css
Labels: fix

#53 토글 컴포넌트 라벨 left, right 속성 제거
  packages/css/component/toggle.css
Labels: fix

#54 토글 컴포넌트 라벨 right, left 제거 문서 반영
  docs/component/toggle.md
Labels: documentation

#55 토글, 텍스트박스 라벨 선택자 클래스 수정
  packages/css/component/text-box.css
  packages/css/component/toggle.css
Labels: fix

#56 fix: 모달 사이즈 속성 제거
  docs/component/overview.md
  packages/css/component/modal.css
Labels: fix

#57 release: 0.1.5
  docs/.vitepress/config.ts
  docs/guide/getting-started.md
  package-lock.json
  package.json
Labels: feature

#58 토글, 텍스트박스 컴포넌트 라벨 버그 및 토글 라벨 폰트 스타일 적용
  packages/css/component/text-box.css
  packages/css/component/toggle.css
Labels: fix

#59 release: 0.1.6
  dist/style.css
  docs/.vitepress/config.ts
  docs/guide/getting-started.md
  package.json
Labels: feature

#60 토글 컴포넌트 문서 수정
  docs/component/toggle.md
Labels: fix

#61 docs: 버튼 컴포넌트
  docs/.vitepress/config.ts
  docs/component/button.md
  package-lock.json
Labels: documentation

#62 토글, 텍스트박스 컴포넌트 라벨 코드 수정
  packages/css/component/text-box.css
  packages/css/component/toggle.css
Labels: fix

#65 align-style css 약어 클래스 수정
  packages/css/component/form.css
  packages/css/util/align-style.css
Labels: fix

#67 docs: 컨테이너
  docs/.vitepress/config.ts
  docs/component/container.md
  packages/css/component/form.css
Labels: documentation, fix

#69 docs: util align-* 약어 클래스 수정
  docs/utility/align-style/align-content.md
  docs/utility/align-style/align-items.md
  docs/utility/align-style/align-self.md
Labels: documentation

#70 border css 약어 클래스 수정
  packages/css/util/border.css
Labels: fix

#71 cursor css 약어 클래스 수정
  packages/css/util/cursor.css
Labels: fix

#72 docs: bg-attch, bg-pos 약어 클래스 추가
  docs/utility/background/background-attachment.md
  docs/utility/background/background-position.md
  packages/css/component/container.css
Labels: documentation

#73 flex css 약어 클래스 수정
  packages/css/util/flex.css
Labels: fix

#75 docs: border-* 계열 약어클래스 수정 및 추가
  docs/utility/border/border-color.md
  docs/utility/border/border-radius.md
  docs/utility/border/border-style.md
  docs/utility/border/border-width.md
  docs/utility/border/border.md
Labels: documentation

#74 gap css 약어 클래스 수정
  packages/css/util/box-sizing.css
  packages/css/util/gap.css
Labels: fix

#76 docs: box-sizing 약어 클래스 제거
  docs/utility/box-sizing.md
  packages/css/util/box-sizing.css
Labels: documentation, fix

#77 font css 약어 클래스 삭제
  packages/css/util/font.css
Labels: fix

#78 cursor css 클래스 수정
  packages/css/util/cursor.css
Labels: fix

#80 docs: flex-* 계열 약어 클래스 수정
  docs/utility/flex/flex-basis.md
  docs/utility/flex/flex-direction.md
  docs/utility/flex/flex-flow.md
  docs/utility/flex/flex-grow.md
  docs/utility/flex/flex-shrink.md
  docs/utility/flex/flex-wrap.md
  docs/utility/flex/flex.md
Labels: documentation

#81 docs: cursor 클래스명 수정
  docs/utility/cursor.md
Labels: documentation

#85 fix: color 반응형 약어 클래스 제거
  packages/css/util/font.css
Labels: fix

#87 docs: gap-* 약어 클래스 수정 및 제거
  docs/utility/gap/column-gap.md
  docs/utility/gap/row-gap.md
Labels: documentation

#95 docs: margin-* 약어 클래스 수정
  docs/utility/margin/margin-bottom.md
  docs/utility/margin/margin-left.md
  docs/utility/margin/margin-right.md
  docs/utility/margin/margin-top.md
Labels: documentation

#99 docs: padding-* 약어 클래스 및 px 표기 수정
  docs/utility/margin/margin-bottom.md
  docs/utility/margin/margin-left.md
  docs/utility/margin/margin-right.md
  docs/utility/margin/margin-top.md
  docs/utility/margin/margin-x.md
  docs/utility/margin/margin-y.md
  docs/utility/margin/margin.md
  docs/utility/padding/padding-bottom.md
  docs/utility/padding/padding-left.md
  docs/utility/padding/padding-right.md
  docs/utility/padding/padding-top.md
  docs/utility/padding/padding-x.md
  docs/utility/padding/padding-y.md
  docs/utility/padding/padding.md
  docs/variables/gap.md
Labels: documentation

#100 docs: object-fit 약어 클래스 수정
  docs/utility/object-fit.md
Labels: documentation

#101 docs: list-style-* 약어 클래스 수정
  docs/utility/list-style/list-style-image.md
  docs/utility/list-style/list-style-position.md
  docs/utility/list-style/list-style-type.md
  docs/utility/list-style/list-style.md
Labels: documentation
